/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeddingSlugRouteImport } from './routes/$weddingSlug'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminGuestsRouteImport } from './routes/admin/guests'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOnboardingRouteImport } from './routes/admin/onboarding'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as ApiPhotoRouteImport } from './routes/api/photo'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as AdminInviteTokenRouteImport } from './routes/admin/invite.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingSlugRoute = WeddingSlugRouteImport.update({
  id: '/$weddingSlug',
  path: '/$weddingSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPhotoRoute = ApiPhotoRouteImport.update({
  id: '/api/photo',
  path: '/api/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInviteTokenRoute = AdminInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$weddingSlug': typeof WeddingSlugRoute
  '/design': typeof DesignRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/photo': typeof ApiPhotoRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invite/$token': typeof AdminInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$weddingSlug': typeof WeddingSlugRoute
  '/design': typeof DesignRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/photo': typeof ApiPhotoRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/invite/$token': typeof AdminInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$weddingSlug': typeof WeddingSlugRoute
  '/design': typeof DesignRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/photo': typeof ApiPhotoRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/invite/$token': typeof AdminInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$weddingSlug'
    | '/design'
    | '/admin/admins'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/onboarding'
    | '/admin/pages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/support'
    | '/api/photo'
    | '/rsvp/$token'
    | '/admin/'
    | '/admin/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$weddingSlug'
    | '/design'
    | '/admin/admins'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/onboarding'
    | '/admin/pages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/support'
    | '/api/photo'
    | '/rsvp/$token'
    | '/admin'
    | '/admin/invite/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$weddingSlug'
    | '/design'
    | '/admin/admins'
    | '/admin/guests'
    | '/admin/login'
    | '/admin/onboarding'
    | '/admin/pages'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/support'
    | '/api/photo'
    | '/rsvp/$token'
    | '/admin/'
    | '/admin/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  WeddingSlugRoute: typeof WeddingSlugRoute
  DesignRoute: typeof DesignRoute
  ApiPhotoRoute: typeof ApiPhotoRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$weddingSlug': {
      id: '/$weddingSlug'
      path: '/$weddingSlug'
      fullPath: '/$weddingSlug'
      preLoaderRoute: typeof WeddingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guests': {
      id: '/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/photo': {
      id: '/api/photo'
      path: '/api/photo'
      fullPath: '/api/photo'
      preLoaderRoute: typeof ApiPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invite/$token': {
      id: '/admin/invite/$token'
      path: '/invite/$token'
      fullPath: '/admin/invite/$token'
      preLoaderRoute: typeof AdminInviteTokenRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInviteTokenRoute: typeof AdminInviteTokenRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminGuestsRoute: AdminGuestsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInviteTokenRoute: AdminInviteTokenRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  WeddingSlugRoute: WeddingSlugRoute,
  DesignRoute: DesignRoute,
  ApiPhotoRoute: ApiPhotoRoute,
  RsvpTokenRoute: RsvpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
